/**@@@+++@@@@******************************************************************
**
** Microsoft (r) PlayReady (r)
** Copyright (c) Microsoft Corporation. All rights reserved.
**
***@@@---@@@@******************************************************************
*/

#ifndef __DRMMODULESUPPORT_H__
#define __DRMMODULESUPPORT_H__

#include <drmsecurecoretypes.h>

ENTER_PK_NAMESPACE;

/***************************************************************************
**
** Declare the DRM_MODULEX_IsModuleXSupported functions for all modules.
**
***************************************************************************/

DRM_API DRM_BOOL DRM_CALL DRM_ARCLK_IsAntirollbackClockSupported();
DRM_API DRM_BOOL DRM_CALL DRM_ARCLK_IsAntirollbackClockUnsupported();

DRM_API DRM_BOOL DRM_CALL DRM_CERTCACHE_IsCertCacheSupported();
DRM_API DRM_BOOL DRM_CALL DRM_CERTCACHE_IsCertCacheUnsupported();

DRM_API DRM_BOOL DRM_CALL DRM_CLEANSTORE_IsCleanStoreSupported();
DRM_API DRM_BOOL DRM_CALL DRM_CLEANSTORE_IsCleanStoreUnsupported();

DRM_API DRM_BOOL DRM_CALL DRM_CONTRACT_IsContractSupported();
DRM_API DRM_BOOL DRM_CALL DRM_CONTRACT_IsContractUnsupported();

DRM_API DRM_BOOL DRM_CALL DRM_CRT_IsCRTSupported();
DRM_API DRM_BOOL DRM_CALL DRM_CRT_IsCRTUnsupported();

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_DEVICEASSETS_IsDeviceAssetsSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_DEVICEASSETS_IsDeviceAssetsUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_DOMAIN_IsDomainSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_API DRM_BOOL DRM_CALL DRM_DOMAIN_IsDomainUnsupported();

DRM_NO_INLINE DRM_API DRM_BOOL DRM_EST_IsESTSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_EST_IsESTUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_API DRM_BOOL DRM_CALL DRM_HDS_IsHDSSupported();
DRM_API DRM_BOOL DRM_CALL DRM_HDS_IsHDSUnsupported();

DRM_API DRM_BOOL DRM_CALL DRM_HBHC_IsHdsBlockHeaderCacheSupported();
DRM_API DRM_BOOL DRM_CALL DRM_HBHC_IsHdsBlockHeaderCacheUnsupported();

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_LICGEN_IsLicGenSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_LICGEN_IsLicGenUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_M2TS_IsM2TSEncryptorSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_M2TS_IsM2TSEncryptorUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_API DRM_BOOL DRM_CALL DRM_METERCERTREVOCATION_IsMeterCertRevocationSupported();
DRM_API DRM_BOOL DRM_CALL DRM_METERCERTREVOCATION_IsMeterCertRevocationUnsupported();

DRM_API DRM_BOOL DRM_CALL DRM_METERING_IsMeteringSupported();
DRM_API DRM_BOOL DRM_CALL DRM_METERING_IsMeteringUnsupported();

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_MODELREVOCATION_IsModelRevocationSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_API DRM_BOOL DRM_CALL DRM_MODELREVOCATION_IsModelRevocationUnsupported();

DRM_API DRM_BOOL DRM_CALL DRM_MOVE_IsMoveSupported();
DRM_API DRM_BOOL DRM_CALL DRM_MOVE_IsMoveUnsupported();

#define DRM_NST_IsNSTSupported()   DRM_EST_IsESTSupported()
#define DRM_NST_IsNSTUnsupported() DRM_EST_IsESTUnsupported()

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_PERSTREAMKEYS_IsPerStreamKeysSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_PERSTREAMKEYS_IsPerStreamKeysUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_PRND_IsPRNDSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_PRND_IsPRNDUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_PRND_IsPRNDTransmitterSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_PRND_IsPRNDTransmitterUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_PRND_IsPRNDReceiverSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_PRND_IsPRNDReceiverUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_REVOCATION_IsRevocationSupported() DRM_NO_INLINE_ATTRIBUTE;
#define DRM_REVOCATION_IsV1RIVSupported(x) DRM_WMDRMNET_IsWmdrmnetSupported(x)

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_CLK_IsSecureClockSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_CLK_IsSecureClockUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_CLK_IsSecureClockExternSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_CLK_IsSecureClockExternUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_SECURESTOP_IsSecureStopSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_SECURESTOP_IsSecureStopUnsupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_THUMBNAIL_IsThumbnailSupported() DRM_NO_INLINE_ATTRIBUTE;
DRM_API DRM_BOOL DRM_CALL DRM_THUMBNAIL_IsThumbnailUnsupported();

DRM_API DRM_BOOL DRM_CALL DRM_WMDRMNET_IsWmdrmnetSupported( __in DRM_SECURECORE_CONTEXT *f_pSecureCoreCtx ) DRM_NO_INLINE_ATTRIBUTE;
DRM_API DRM_BOOL DRM_CALL DRM_WMDRMNET_IsWmdrmnetSupported_NoContext() DRM_NO_INLINE_ATTRIBUTE;

DRM_API DRM_BOOL DRM_CALL DRM_XMLHASH_IsXmlHashSupported();
DRM_API DRM_BOOL DRM_CALL DRM_XMLHASH_IsXmlHashUnsupported();

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_H264_IsSupported() DRM_NO_INLINE_ATTRIBUTE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_COCKTAIL_IsSupported() DRM_NO_INLINE_ATTRIBUTE;

EXIT_PK_NAMESPACE;

#endif  /* __DRMMODULESUPPORT_H__ */

