/*
 * (C) Copyright 2007-2011
 * Allwinner Technology Co., Ltd. <www.allwinnertech.com>
 * Tom Cubie <tangliang@allwinnertech.com>
 *
 * Boot an image which is generated by android mkbootimg tool
 *
 * (C) Copyright 2000-2003
 * Wolfgang Denk, DENX Software Engineering, wd@denx.de.
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

/*
 * Misc boot support
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <android_image.h>
#include <image.h>
#include <boot_akernel.h>
#include <sunxi_boot_api.h>

static int android_image_get_signature(const struct andr_img_hdr *hdr, unsigned long *sign_data, unsigned long *sign_len)
{
	struct boot_img_hdr_ex  *hdr_ex;
	unsigned long addr=0;

	hdr_ex = (struct boot_img_hdr_ex *)hdr;
	if(strncmp((void *)(hdr_ex->cert_magic),AW_CERT_MAGIC,strlen(AW_CERT_MAGIC))){
		printf("No cert image embeded, image %s\n",hdr_ex->cert_magic);
		return 0;
	}

	addr = (unsigned long)hdr;

	addr += hdr->page_size;
	addr += ALIGN(hdr->kernel_size, hdr->page_size);
	addr += ALIGN(hdr->ramdisk_size, hdr->page_size);
	if(hdr->second_size)
		addr += ALIGN(hdr->second_size, hdr->page_size);

	*sign_data = (unsigned long)addr;
	*sign_len = hdr_ex->cert_size;
	memset(hdr_ex->cert_magic,0,ANDR_BOOT_MAGIC_SIZE+sizeof(unsigned));
	return 1;
}

void * memcpy2(void * dest,const void * src, unsigned int n)
{
	if (src == dest)
		return dest;
	if (src < dest) {
		if ( (unsigned int )src + n > (unsigned int)dest) {
			memcpy((void*) (dest + (dest - src)), dest, src + n - dest);
			n = dest - src;
		}
		memcpy(dest, src, n);
	} else {
		memcpy(dest, src, n);
	}
	return dest;
}


/*  parse the android format kernel image and then verity the interity
 *
 * arguments:
 * image_buf : 0x45000000( image address in DRAM)
 * name : image name which should be "kernel" or "recovery" 
 */

int do_boota (void *image_buf, void *toc1_buf, char *name)
{

    //if soc is not secure then should not verify boot.img
    if (check_soc_is_secure() == 0){
        printf("it's normal soc,needn't verify boot.img'\n");
        return 0;
    }
	unsigned long os_load_addr;
	struct  andr_img_hdr *fb_hdr = NULL;

	os_load_addr = (unsigned long)image_buf; 
	fb_hdr = (struct andr_img_hdr *)os_load_addr;

	if(android_image_check_header(fb_hdr))
	{
		printf("boota: bad boot image magic, maybe not a boot.img?\n");
		return -1;
	}

	/*verity the signature*/
	{
		unsigned long total_len = ALIGN(fb_hdr->ramdisk_size, fb_hdr->page_size) + 	\
		                  ALIGN(fb_hdr->kernel_size, fb_hdr->page_size)  +  \
		                  fb_hdr->page_size;

		printf("total_len=%d\n", (unsigned int)total_len);
		unsigned long sign_data , sign_len;
		int ret ;

		ret = android_image_get_signature(fb_hdr,&sign_data,&sign_len);
		if(!ret)
		{
			printf("boota: verify the %s failed\n", name);
			return 1;
		}
		ret = sunxi_verify_embed_signature((void*)os_load_addr, (void*)toc1_buf, (unsigned int)total_len,\
												name,(void *)sign_data,sign_len);
		if(ret)
		{
			printf("boota: verify the %s failed\n", name);
			return 1;
		}
	}

	printf("verify boot.img succeed, continue the upgrade process.\n");

	return 0;
}


