
#ifndef _SUPPORT_COMMANDS_H
#define _SUPPORT_COMMANDS_H

#define __MAKE_CMD_CODE(__cmd, __index) \
	(((__cmd) << 8) | (__index))

#define CMD_IFACE				(0x10)
#define CMD_IFACE_GET_FORMAT	__MAKE_CMD_CODE(CMD_IFACE, 1)
#define CMD_IFACE_SET_FORMAT	__MAKE_CMD_CODE(CMD_IFACE, 2)
#define CMD_IFACE_GET_TYPE		__MAKE_CMD_CODE(CMD_IFACE, 3)
#define CMD_IFACE_GET_MODE		__MAKE_CMD_CODE(CMD_IFACE, 4)
#define CMD_IFACE_SET_MODE		__MAKE_CMD_CODE(CMD_IFACE, 5)
#define CMD_IFACE_LIST_MODE		__MAKE_CMD_CODE(CMD_IFACE, 6)
#define CMD_IFACE_CHECK_MODE	__MAKE_CMD_CODE(CMD_IFACE, 7)
#define CMD_IFACE_GET_PIXEL_FORMAT       __MAKE_CMD_CODE(CMD_IFACE, 8)
#define CMD_IFACE_SET_PIXEL_FORMAT       __MAKE_CMD_CODE(CMD_IFACE, 9)
#define CMD_IFACE_GET_CUR_DATASPACE_MODE __MAKE_CMD_CODE(CMD_IFACE, 10)
#define CMD_IFACE_GET_DATASPACE_MODE     __MAKE_CMD_CODE(CMD_IFACE, 11)
#define CMD_IFACE_SET_DATASPACE_MODE     __MAKE_CMD_CODE(CMD_IFACE, 12)
#define CMD_IFACE_GET_DEVICE_CONFIG      __MAKE_CMD_CODE(CMD_IFACE, 13)
#define CMD_IFACE_SET_DEVICE_CONFIG      __MAKE_CMD_CODE(CMD_IFACE, 14)

#define CMD_3DMODE				(0x20)
#define CMD_3DMODE_GET_MODE		__MAKE_CMD_CODE(CMD_3DMODE, 1)
#define CMD_3DMODE_SET_MODE		__MAKE_CMD_CODE(CMD_3DMODE, 2)
#define CMD_3DMODE_SET_LAYER_OFFSET	__MAKE_CMD_CODE(CMD_3DMODE, 3)

#define CMD_OVERSCAN			(0x30)
#define CMD_OVERSCAN_GET_MARGIN	__MAKE_CMD_CODE(CMD_OVERSCAN, 1)
#define CMD_OVERSCAN_SET_MARGIN	__MAKE_CMD_CODE(CMD_OVERSCAN, 2)
#define CMD_OVERSCAN_GET_OFFSET	__MAKE_CMD_CODE(CMD_OVERSCAN, 3)
#define CMD_OVERSCAN_SET_OFFSET	__MAKE_CMD_CODE(CMD_OVERSCAN, 4)

#define CMD_ENHANCE				(0x40)
#define CMD_ENHANCE_GET_EDGE	__MAKE_CMD_CODE(CMD_ENHANCE, 1)
#define CMD_ENHANCE_SET_EDGE	__MAKE_CMD_CODE(CMD_ENHANCE, 2)
#define CMD_ENHANCE_GET_DETAIL	__MAKE_CMD_CODE(CMD_ENHANCE, 3)
#define CMD_ENHANCE_SET_DETAIL	__MAKE_CMD_CODE(CMD_ENHANCE, 4)
#define CMD_ENHANCE_GET_BRIGHT	__MAKE_CMD_CODE(CMD_ENHANCE, 5)
#define CMD_ENHANCE_SET_BRIGHT	__MAKE_CMD_CODE(CMD_ENHANCE, 6)
#define CMD_ENHANCE_GET_DENOISE	__MAKE_CMD_CODE(CMD_ENHANCE, 7)
#define CMD_ENHANCE_SET_DENOISE	__MAKE_CMD_CODE(CMD_ENHANCE, 8)
#define CMD_ENHANCE_GET_CONTRAST	__MAKE_CMD_CODE(CMD_ENHANCE,  9)
#define CMD_ENHANCE_SET_CONTRAST	__MAKE_CMD_CODE(CMD_ENHANCE, 10)
#define CMD_ENHANCE_GET_SATURATION	__MAKE_CMD_CODE(CMD_ENHANCE, 11)
#define CMD_ENHANCE_SET_SATURATION	__MAKE_CMD_CODE(CMD_ENHANCE, 12)
#define CMD_ENHANCE_GET_MODE		__MAKE_CMD_CODE(CMD_ENHANCE, 13)
#define CMD_ENHANCE_SET_MODE		__MAKE_CMD_CODE(CMD_ENHANCE, 14)

#define CMD_UTILS               (0x50)
#define CMD_UTILS_SET_3D_LAYER_MODE    __MAKE_CMD_CODE(CMD_UTILS, 1)
#define CMD_UTILS_SET_3D_LAYER_OFFSET  __MAKE_CMD_CODE(CMD_UTILS, 2)
#define CMD_UTILS_GET_SUPPORT_3D_MODE  __MAKE_CMD_CODE(CMD_UTILS, 3)

#endif
